# frozen_string_literal: true

source 'https://rubygems.org'
gem 'bootsnap', require: false
gem 'bcrypt'
gem 'byebug', platforms: %i[mri mingw x64_mingw]
gem 'factory_bot_rails'
gem 'faker'
gem 'jwt'
gem 'listen'
gem 'overcommit'
gem 'pg'
gem 'pry'
gem 'pry-byebug'
gem 'pry-stack_explorer'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rails'
gem 'rspec-rails'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'rubocop-thread_safety'
gem 'spreadsheet'
gem 'spring'
gem 'spring-watcher-listen'
